### ISSUE TITLE
ArrayIndexOutOfBoundsException in JMLPattern.getPropDef

### ISSUE THREAD

**Issue by jkboyce** [jkboyce/jugglinglab#50]
Co-creator of the Android version of Juggling Lab, I get a lot of reports (14 so far) for an error that seems to be caused by Juggling Lab itself and not our Android version.

Here is the stack trace:
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
at java.util.Vector.elementAt(Vector.java:326)
at com.jonglen7.jugglinglab.jugglinglab.jml.JMLPattern.getPropDef(JMLPattern.java:916)
at com.jonglen7.jugglinglab.jugglinglab.jml.JMLPattern.getProp(JMLPattern.java:913)
at com.jonglen7.jugglinglab.jugglinglab.renderer.JugglingRenderer.drawEffectiveFrame(JugglingRenderer.java:333)
at com.jonglen7.jugglinglab.jugglinglab.renderer.JugglingRenderer.onDrawFrame(JugglingRenderer.java:239)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1516)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

Looks like JMLPattern.getPropDef is called with an argument that has a value of zero, I wasn't able to reproduce the bug and the users didn't say how they got it so I'm not sure what to look for.Most patterns work so it might be linked to a specific pattern, the question is which one.

Any help appreciated.

My email is romain.richard.IT.engineer@gmail.com

Reported by: romainrichard

**Comment by jkboyce** [comment]
Going to close this for now since I've never seen a way to reproduce it.
